// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB04kD3c4lMD3GKehr7rJ7AbQxVTtg3u_Y',
    appId: '1:299588189133:web:57281c22b7e48ccaf4a284',
    messagingSenderId: '299588189133',
    projectId: 'appesentics',
    authDomain: 'appesentics.firebaseapp.com',
    storageBucket: 'appesentics.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaBgwFaQ_Wut734RMdKI3xiAcybpTjg7k',
    appId: '1:299588189133:android:5b42ce2aa5a4a649f4a284',
    messagingSenderId: '299588189133',
    projectId: 'appesentics',
    storageBucket: 'appesentics.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJdXAUB5P153Kbenh3VBrJV7xAu2Yf-hM',
    appId: '1:299588189133:ios:18a252249a78fc22f4a284',
    messagingSenderId: '299588189133',
    projectId: 'appesentics',
    storageBucket: 'appesentics.firebasestorage.app',
    iosBundleId: 'com.example.flutterAppEjercicio3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJdXAUB5P153Kbenh3VBrJV7xAu2Yf-hM',
    appId: '1:299588189133:ios:18a252249a78fc22f4a284',
    messagingSenderId: '299588189133',
    projectId: 'appesentics',
    storageBucket: 'appesentics.firebasestorage.app',
    iosBundleId: 'com.example.flutterAppEjercicio3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB04kD3c4lMD3GKehr7rJ7AbQxVTtg3u_Y',
    appId: '1:299588189133:web:9f5dba661383838bf4a284',
    messagingSenderId: '299588189133',
    projectId: 'appesentics',
    authDomain: 'appesentics.firebaseapp.com',
    storageBucket: 'appesentics.firebasestorage.app',
  );
}
